version: "3.8"

services:
  apply-classic-page:
    build:
      context: ./custom-universal-login
      dockerfile: Dockerfile
    env_file: .env
  update-settings:
    build:
      context: ./orchestrator
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - ./product-a-regular-web-app:/app/envs/product-a
      - ./product-b-regular-web-app:/app/envs/product-b
      - ./product-c-single-page-app:/app/envs/product-c
      - ./django-api:/app/envs/django-api
  django-api:
    build:
      context: django-api
    env_file: django-api/.env.development
    ports:
      - "8010:8010"
  product-a:
    build:
      context: product-a-regular-web-app
    env_file: product-a-regular-web-app/.env.development
    ports:
      - "8000:8000"
  product-b:
    build:
      context: product-b-regular-web-app
    env_file: product-b-regular-web-app/.env.development
    ports:
      - "8001:8001"
  product-c:
    build:
      context: product-c-single-page-app
    env_file: product-c-single-page-app/.env.development
    ports:
      - "8002:8002"
