version: "3.8"

services:
  apply-classic-page:
    build:
      context: ./custom-universal-login
      dockerfile: Dockerfile
    env_file: custom-universal-login/.env.development
  update-settings:
    build:
      context: ./orchestrator
      dockerfile: Dockerfile
    env_file: orchestrator/.env.development
    volumes:
      # Will add more as soon as they're available
      - ./product-a-regular-web-app:/app/product-a
      - ./product-b-regular-web-app:/app/product-b
      - ./product-c-single-page-app:/app/product-c
  product-a:
    build:
      context: product-a-regular-web-app
    env_file: product-a-regular-web-app/.env.development
    ports:
      - "8000:8000"
  product-b:
    build:
      context: product-b-regular-web-app
    env_file: product-b-regular-web-app/.env.development
    ports:
      - "8001:8001"
  product-c:
    build:
      context: product-c-single-page-app
    env_file: product-c-single-page-app/.env.development
    ports:
      - "8002:8002"
